### ISSUE TITLE
Modified and saved

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [emacs-vs/line-reminder#20]
I just noticed something that might not be an issue or might be one, depending on how one understands "modified" and "saved":

Original code:

![image](https://user-images.githubusercontent.com/11130348/210231748-2e40f75b-dffe-42d4-b286-1a9c23982d95.png)

When I change a  file the changed marker (yellow) appears:

![image](https://user-images.githubusercontent.com/11130348/210231677-bc6e7a49-0585-427b-b0aa-93900d9a65f1.png)

When I then remove the inserted empty line and save the file, my Emacs is configured to remove trailing whitespace (this might be a cause!) and then actually save the file. However even if nothing compared to the original version is truly changed, the green bar ("saved") remains:

![image](https://user-images.githubusercontent.com/11130348/210231859-44c6cb39-2d24-4432-8d97-181ea49cd824.png)

Is this intentional and would it not be better to compare with the previously saved file? I guess that would incur a higher cost though than reacting merely to line changes of the already opened buffer/file.

**Comment by jcs090218** [comment]
Yeah, this is intentional and we are not comparing the previously saved file. It only add/remove lines while making changes.

**Comment by ZelphirKaltstahl** [comment]
OK thanks for the quick response!
