### ISSUE TITLE
Question: What dictates if there are  spaces between indicators?

### ISSUE THREAD

**Issue by chookity-pokk** [emacs-vs/line-reminder#25]
For example, the Emacs screenshot used in the README show spaces between each yellow/green indicator. That is the same for my setup, but if I launch Emacs with `emacs -Q` and run the line-reminder section of my init it shows it as a single block, similar to the visual studio  screenshot. 

So what is it that decides if there will be a space or not?

**Comment by jcs090218** [comment]
If you are using `linum`, it's effect by: (the screenshot is actually from `linum`, it's an old screenshot 😅)

https://github.com/emacs-vs/line-reminder/blob/ea916b5c040cbc7e39b46c1137b4d0bf5c19a241/line-reminder.el#L88-L106

For `indicators`, it's a bitmap:

https://github.com/emacs-vs/line-reminder/blob/ea916b5c040cbc7e39b46c1137b4d0bf5c19a241/line-reminder.el#L114-L118

**Comment by chookity-pokk** [comment]
So how would I change it so there isn't a gap between the indicators?

**Comment by jcs090218** [comment]
For `linum`, it depends on the character and your font! You will need to tweak to fit them well.

For `indicators`, you can create your own bitmap and assign it to `line-reminder-bitmap`.

```elisp
(fringe-helper-define 'my-line-reminder-bitmap nil
  "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.."
  "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.."
  "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.."
  "..xxx.." "..xxx.."  ; original bitmap stops here
  "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." 
  "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.." "..xxx.."  ; add a tone to make it longer
)

(setq line-reminder-bitmap 'my-line-reminder-bitmap)
```

**Comment by chookity-pokk** [comment]
Thank you very much! I use indicators so the bitmap worked for me!

**Comment by chookity-pokk** [comment]
Also, I'd just like to thank you in general for all the work you do in the Emacs community. I swear no matter where I go I am always seeing your name. Thank you very much for your work and contributions!
