### ISSUE TITLE
not working in doom emacs

### ISSUE THREAD

**Issue by Aneeqasif** [emacs-vs/line-reminder#29]
i am sorry if my question is very  noob but i have installed it using 
```lisp
(package! line-reminder)
(global-line-reminder-mode t)
```
and the modified or changes are not showing up in left of the window ie in gutter as shown in readme. please let me know whats i am missing here

**Comment by jcs090218** [comment]
I guess you don't use `linum-mode`, try `(setq line-reminder-show-option 'indicators)`.

**Comment by Aneeqasif** [comment]
yes it is working with indicators but i really want to change the default bitmap which seems not possible and the linum mode is not working

**Comment by jcs090218** [comment]
> i really want to change the default bitmap which seems not possible

You can create bitmap and assign it to the variable `line-reminder-bitmap`.

> linum mode is not working

`linum-mode` is deprecated, so we will plan to remove it in the future. See https://github.com/emacs-vs/line-reminder/blob/1835ea7dbd4943a165c9786d19cebaceff170a71/line-reminder.el#L114C1-L123C25.

> another thing is that i didnt understand the thumbnail feature form readme can you please explain a bit

The core shows precisely where the lines have been edited. The thumbnail shows the edit throughout the document. By default, the core feature is on the left, and the thumbnail feature is on the right.

<img src="https://github.com/emacs-vs/line-reminder/assets/8685505/0d18e10b-b096-44a8-9109-58fb7d0f5b4d" width="50%" />

**Comment by Aneeqasif** [comment]
ah thanks for the explanation got it

**Comment by Aneeqasif** [comment]
> You can create bitmap 
btw is it possible to have a bitmap that donot have verticle gaps and make it look like a continuous line just like visual studio or other git  highlight plugins that give similar feature but in refrence to git changes and uncommited blocks

**Comment by jcs090218** [comment]
Yes. I think it depends on the font you are using. See below:

![2023-11-15 03 34 08](https://github.com/emacs-vs/line-reminder/assets/8685505/ddb973a3-93a9-4080-b1d4-d9d3276359e4)

**Comment by Aneeqasif** [comment]
> Yes. I think it depends on the font you are using. See below:

do this work with following settings? as indicators use bitmaps arent they font independent?

```lisp
(global-line-reminder-mode t)
(setq line-reminder-show-option 'indicators)
```

**Comment by jcs090218** [comment]
You should probably have `setq` at the top:

```
(setq line-reminder-show-option 'indicators)
(global-line-reminder-mode t)
```

> one other thins is i donot want to enable it globally as it also enable itself in terminal modes how can i enable it in the buffers/mode in which i code like python rust markdown org etc

You will need to customize it yourself. For example, the following will enable this package for all major-mode derived from `prog-mode`, which most programming-driven major-mode do.

```elisp
(add-hook 'prog-mode-hook #'line-reminder-mode)
```
